spring:
  application:
    name: alert-consumer
  datasource:
    url: jdbc:postgresql://localhost:5432/observability
    username: obs_user
    password: obs_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    enabled: false

logging:
  level:
    com.thinhbui303.observability: DEBUG
    org.springframework.kafka: INFO
