server:
  port: 8082
spring:
  application:
    name: indexer-worker
  
  kafka:
    bootstrap-servers: localhost:9092
    
  elasticsearch:
    uris: http://localhost:9200
    
logging:
  level:
    com.thinhbui303.observability: DEBUG
    org.springframework.kafka: INFO
