server:
  port: 8083

spring:
  application:
    name: analytics-engine
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/observability
    username: ${POSTGRES_USER:obs_user}
    password: ${POSTGRES_PASSWORD:obs_password}
    driver-class-name: org.postgresql.Driver

analytics:
  rule:
    cache:
      refresh-rate: 30000
